sudo: false
language: node_js
node_js:
  - "8.3"
notifications:
  disabled: true

before_install:
  - npm install -g codecov
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      npm i -g glitch-deploy;
    fi

install:
  - npm install

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script:
  - npm test
  - codecov

after_success:
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      glitch-deploy;
    fi